export const statesWithDistricts = {
  Gujarat: [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Gandhinagar",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Anand",
    "Kheda",
  ],
  Maharashtra: [
    "Mumbai City",
    "Pune",
    "Nagpur",
    "Thane",
    "Nashik",
    "Aurangabad",
    "Solapur",
    "Amravati",
    "Kolhapur",
    "Sangli",
  ],
  Rajasthan: [
    "Jaipur",
    "Udaipur",
    "Jodhpur",
    "Kota",
    "Bikaner",
    "Ajmer",
    "Alwar",
    "Chittorgarh",
    "Sikar",
    "Jhunjhunu",
  ],
  "Uttar Pradesh": [
    "Agra",
    "Aligarh",
    "Allahabad",
    "Azamgarh",
    "Bareilly",
    "Basti",
    "Bijnor",
    "Etah",
    "Etawah",
    "Faizabad",
  ],
  "Madhya Pradesh": [
    "Bhopal",
    "Indore",
    "Gwalior",
    "Jabalpur",
    "Ujjain",
    "Rewa",
    "Sagar",
    "Satna",
    "Sehore",
    "Ratlam",
  ],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Vellore",
    "Erode",
    "Thanjavur",
    "Dindigul",
    "Thoothukudi",
  ],
  "West Bengal": [
    "Kolkata",
    "Howrah",
    "Darjeeling",
    "Hooghly",
    "Nadia",
    "North 24 Parganas",
    "South 24 Parganas",
    "Murshidabad",
    "Burdwan",
    "Malda",
  ],
  Karnataka: [
    "Bangalore Urban",
    "Mysuru",
    "Hubli-Dharwad",
    "Belagavi",
    "Mangaluru",
    "Tumakuru",
    "Ballari",
    "Kalaburagi",
    "Davangere",
    "Hassan",
  ],
  Kerala: [
    "Thiruvananthapuram",
    "Ernakulam",
    "Kozhikode",
    "Malappuram",
    "Thrissur",
    "Kollam",
    "Palakkad",
    "Kottayam",
    "Alappuzha",
    "Pathanamthitta",
  ],
  "Andhra Pradesh": [
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Kurnool",
    "Nellore",
    "Chittoor",
    "Kadapa",
    "Anantapur",
    "Srikakulam",
    "West Godavari",
  ],
  Telangana: [
    "Hyderabad",
    "Warangal",
    "Khammam",
    "Karimnagar",
    "Nizamabad",
    "Mahabubnagar",
    "Medak",
    "Rangareddy",
    "Adilabad",
    "Nalgonda",
  ],
  Bihar: [
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Purnia",
    "Darbhanga",
    "Munger",
    "Nalanda",
    "Begusarai",
    "Saran",
  ],
  Punjab: [
    "Amritsar",
    "Ludhiana",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Mohali",
    "Hoshiarpur",
    "Rupnagar",
    "Firozpur",
    "Faridkot",
  ],
  Haryana: [
    "Ambala",
    "Faridabad",
    "Gurgaon",
    "Hisar",
    "Karnal",
    "Kurukshetra",
    "Panchkula",
    "Panipat",
    "Sirsa",
    "Sonipat",
  ],
  Odisha: [
    "Bhubaneswar",
    "Cuttack",
    "Berhampur",
    "Rourkela",
    "Sambalpur",
    "Balasore",
    "Jeypore",
    "Puri",
    "Baripada",
    "Bhadrak",
  ],
  Assam: [
    "Guwahati",
    "Jorhat",
    "Dibrugarh",
    "Silchar",
    "Nagaon",
    "Tinsukia",
    "Bongaigaon",
    "Barpeta",
    "Nalbari",
    "Sivasagar",
  ],
  Chhattisgarh: [
    "Raipur",
    "Bilaspur",
    "Durg",
    "Korba",
    "Rajnandgaon",
    "Raigarh",
    "Jagdalpur",
    "Ambikapur",
    "Kanker",
    "Mahasamund",
  ],
  Jharkhand: [
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro",
    "Hazaribagh",
    "Deoghar",
    "Dumka",
    "Giridih",
    "Koderma",
    "Palamu",
  ],
  Uttarakhand: [
    "Dehradun",
    "Haridwar",
    "Nainital",
    "Udham Singh Nagar",
    "Pauri Garhwal",
    "Almora",
    "Tehri Garhwal",
    "Rudraprayag",
    "Champawat",
    "Bageshwar",
  ],
  "Himachal Pradesh": [
    "Shimla",
    "Solan",
    "Mandi",
    "Kangra",
    "Kullu",
    "Una",
    "Bilaspur",
    "Hamirpur",
    "Sirmaur",
    "Chamba",
  ],
  "Jammu & Kashmir": [
    "Srinagar",
    "Jammu",
    "Anantnag",
    "Baramulla",
    "Pulwama",
    "Budgam",
    "Kathua",
    "Rajouri",
    "Udhampur",
    "Samba",
  ],
  Goa: ["North Goa", "South Goa"],
  "Arunachal Pradesh": [
    "Itanagar",
    "Tawang",
    "West Kameng",
    "East Kameng",
    "Papum Pare",
    "Lower Subansiri",
    "Upper Subansiri",
    "West Siang",
    "East Siang",
    "Lohit",
  ],
  Mizoram: [
    "Aizawl",
    "Champhai",
    "Kolasib",
    "Lawngtlai",
    "Lunglei",
    "Mamit",
    "Saiha",
    "Serchhip",
  ],
  Nagaland: [
    "Kohima",
    "Dimapur",
    "Mokokchung",
    "Mon",
    "Peren",
    "Phek",
    "Tuensang",
    "Wokha",
    "Zunheboto",
  ],
  Manipur: [
    "Imphal West",
    "Imphal East",
    "Bishnupur",
    "Thoubal",
    "Churachandpur",
    "Ukhrul",
    "Senapati",
    "Tamenglong",
    "Chandel",
    "Tengnoupal",
  ],
  Meghalaya: [
    "East Khasi Hills",
    "West Khasi Hills",
    "Jaintia Hills",
    "Ri Bhoi",
    "West Garo Hills",
    "East Garo Hills",
    "South Garo Hills",
    "North Garo Hills",
  ],
  Tripura: [
    "West Tripura",
    "Sepahijala",
    "Khowai",
    "Gomati",
    "South Tripura",
    "Dhalai",
    "Unakoti",
    "North Tripura",
  ],
  Sikkim: ["East Sikkim", "West Sikkim", "South Sikkim", "North Sikkim"],
  Ladakh: ["Leh", "Kargil"],
  Lakshadweep: ["Lakshadweep"],
  "Andaman & Nicobar Islands": [
    "Nicobar",
    "North and Middle Andaman",
    "South Andaman",
  ],
  Delhi: [
    "Central Delhi",
    "East Delhi",
    "New Delhi",
    "North Delhi",
    "North East Delhi",
    "North West Delhi",
    "Shahdara",
    "South Delhi",
    "South East Delhi",
    "South West Delhi",
    "West Delhi",
  ],
  Puducherry: ["Puducherry", "Karaikal", "Mahe", "Yanam"],
};
